project:
  type: website
  output-dir: docs

website:
  title: "Tutorial on Clone-Censor-Weight"
  announcement: 
    icon: info-circle
    dismissable: true
    content: "**Alert** - This is a work-in-progress, errors may exist in code"
    type: primary
    position: below-navbar
  sidebar: 
    style: 'docked'
    search: true
    contents:
      - text: "Introduction"
        href: qmd/index.qmd
      - section: 'Survival Analysis'
        href: qmd/surv_00_summ.qmd
        contents:
        - text: 'Kaplan-Meier Estimator'
          href: qmd/surv_01_kaplan.qmd
        - qmd/surv_02_disctime.qmd
      - section: 'Cloning-Censoring-Weighting'
        href: qmd/ccw_00_summ.qmd
        contents:
        - qmd/ccw_01_intro.qmd
        - qmd/ccw_02_est.qmd
        - qmd/ccw_03_inf.qmd
        - qmd/ccw_04_diag.qmd
      - section: 'Appendix'
        href: qmd/app_00_summ.qmd
        contents:
        - qmd/app_01_syndata.qmd
        - qmd/app_02_boot.qmd
        - qmd/app_03_speed.qmd
      - text: 'About'
        href: qmd/about.qmd
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



