project:
  type: website
  output-dir: docs

website:
  title: "Tutorial on Clone-Censor-Weight"
  announcement: 
    icon: info-circle
    dismissable: true
    content: "**Alert** - This is a work-in-progress, errors may exist in code"
    type: primary
    position: below-navbar
  sidebar: 
    style: 'docked'
    search: true
    contents:
      - text: Home
        href: index.qmd
      - section: 'Survival Analysis'
        href: 'surv_summ.qmd'
        contents:
        - surv_kaplan.qmd
        - surv_disctime.qmd
      - section: 'Cloning-Censoring-Weighting'
      - href: 'ccw_summ.qmd'
        contents:
        - ccw_00_intro.qmd
        - ccw_01_est.qmd
        - ccw_02_inf.qmd
        #- ccw_03_diag.qmd
      - section: 'Appendix' 
      - href: 'app_summ.qmd'
        contents: 
        - app_01_syndata.qmd
        - app_02_boot.qmd
        - app_03_speed.qmd
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



